language: php
php:
  - '7.1'

sudo: false
dist: trusty

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/phan-ast/build
    - $HOME/.phan-ci

before-install:
  - pecl install ast

install:
  - composer install

script:
  ./vendor/bin/phan
