language: php
php:
  - '7.1'

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

before-install:
  - ./tests/travis_setup.sh
  - composer self-update

install:
  - composer install

script:
  ./vendor/bin/phan
