language: php
php:
  - '7.1'

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - phpize
  - ./configure
  - make
  - make install
  - echo "extension=ast.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before-install:
  - composer self-update

install:
  - composer install

script:
  ./vendor/bin/phan
