language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'

sudo: false
dist: trusty

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/phan-ast/build
    - $HOME/.phan-ci

before-install:
  - ./tests/travis_setup.sh

install:
  - composer install

script:
  ./vendor/bin/phan
